### ISSUE TITLE
内閣府の国民の祝日データと合わない日がある（1990年～2021年のうち4日間）

### ISSUE THREAD

**Issue by sakurai-youhei** [Lalcs/jpholiday#14]
内閣府の[国民の祝日データ](https://www8.cao.go.jp/chosei/shukujitsu/syukujitsu.csv)と合わない日

1. 1992-05-06
2. 1997-05-04
3. 1998-05-06
4. 2003-05-04

jpholidayのバージョン: 0.1.4

私事ですが、ここ数日で[python-shukujitsu](https://github.com/sakurai-youhei/python-shukujitsu)というライブラリを書いたので、それとこのjpholidayとの[クロスバリデーション](https://gist.github.com/sakurai-youhei/a15ff005ee18d69a073d90246bfd67ef#file-xvalid-with-jpholiday-1990-to-2021-py)を実施したところ、上記の4日間、jpholidayでのみ祝日と判定されました。

<img width="164" alt="1992-05-06" src="https://user-images.githubusercontent.com/721858/99664357-6bb91d00-2aab-11eb-9527-b1c3108894de.PNG">
<img width="161" alt="1997-05-04" src="https://user-images.githubusercontent.com/721858/99664387-74a9ee80-2aab-11eb-8dc7-320b15380131.PNG">
<img width="161" alt="1998-05-06" src="https://user-images.githubusercontent.com/721858/99664409-7a073900-2aab-11eb-946f-3f80d3b83707.PNG">
<img width="160" alt="2003-05-04" src="https://user-images.githubusercontent.com/721858/99664415-7c699300-2aab-11eb-9aa7-83a54f04fe90.PNG">

いずれの日もゴールデンウィーク期間中の日曜日、もしくは水曜日ですので、振替休日等の計算に何かしらのコーナーケースや例外があるのかもしれないと感じました。以上、ご報告までに。

**Comment by Lalcs** [comment]
ご連絡ありがとうございます！  
確認して修正したいと思います！

**Comment by sakurai-youhei** [comment]
**問題のコード**

```python
import jpholiday
from datetime import date

print(jpholiday.is_holiday(date(1992, 5, 6)))  # 実際: True 期待: False
print(jpholiday.is_holiday(date(1997, 5, 4)))  # 実際: True 期待: False
print(jpholiday.is_holiday(date(1998, 5, 6)))  # 実際: True 期待: False
print(jpholiday.is_holiday(date(2003, 5, 4)))  # 実際: True 期待: False
```

- [1992年5月の祝日](https://github.com/sakurai-youhei/python-shukujitsu/blob/main/shukujitsu/asof20201118/syukujitsu.csv#L461)
- [1997年5月の祝日](https://github.com/sakurai-youhei/python-shukujitsu/blob/main/shukujitsu/asof20201118/syukujitsu.csv#L540)
- [1998年5月の祝日](https://github.com/sakurai-youhei/python-shukujitsu/blob/main/shukujitsu/asof20201118/syukujitsu.csv#L556)
- [2003年5月の祝日](https://github.com/sakurai-youhei/python-shukujitsu/blob/main/shukujitsu/asof20201118/syukujitsu.csv#L640)

**Comment by Lalcs** [comment]
v0.1.5のリリースにて解消しましたのでクローズとさせていただきます。
詳細な情報とご連絡ありがとうございました！
