### ISSUE TITLE
_to_date() 関数の型チェックを通らないケースがある

### ISSUE THREAD

**Issue by otsuka** [Lalcs/jpholiday#24]
jpholiday を活用させてもらっています。

0.1.5 から 0.1.7 にアップデートしてから、アプリケーションのテストでエラーが発生するようになり、調べていたところ
https://github.com/Lalcs/jpholiday/commit/e4e51f8c2a04d11eff0a4ac33db5578f8391c1d6#diff-3eb44a14116fd7cebc4b4c3347aaca4726cad6b18d083021f8227080181367e0R106-R115
こちらの変更で型チェックが入るようになったのが原因でした。

[freezegun](https://github.com/spulec/freezegun) という Fake の date オブジェクトを生成するテストツールと合わせて使っているのですが、次のテストコードで `_to_date()` 関数から `JPHolidayTypeError` が送出されるエラーを再現できます。

```py
class TestFreezegun(unittest.TestCase):

    def setUp(self) -> None:
        self.the_date = datetime.date(2020, 7, 24)

    @freezegun.freeze_time('2020-7-24')
    def test_freezegun_date(self):
        today = datetime.date.today()
        self.assertTrue(jpholiday.is_holiday(today))

        # this raises "jpholiday.exception.JPHolidayTypeError: is type datetime or date only."
        self.assertTrue(jpholiday.is_holiday(self.the_date))
```

`_to_date()` 関数内の型チェックを `type(value) is ...` から `isinstance(value, ...)` 関数を使う形に変更すれば、上記のテストも通るようになります。

freezegun を使うと、`datetime.date` や `datetime.datetime` が `FakeDate` や `FakeDatetime`といったクラスに置き換えられるのですが、タイミングによって(上のテストの例だと `setUp()` で生成された `datetime.date`)は置き換えられないため、`is` 左辺の `type(value)` は素の `datetime.date` で、右辺の `datetime.date` は `FakeDate` なため if 文が True にならないためにエラーになります。

```py
    if type(value) is datetime.date:
        return value
    if type(value) is datetime.datetime:
        return value.date()
```

上のコードが下のように変更されると自分の問題は解決するのですが、ご検討いただけると幸いです。

```py
    if isinstance(value, datetime.datetime):
        return value.date()
    if isinstance(value, datetime.date):
        return value
```

**Comment by Lalcs** [comment]
v0.18で対応したのでクローズします。
PRありがとうございました！
