### ISSUE TITLE
最新のTag versionがReleaseに記載のあるversionと異なっております

### ISSUE THREAD

**Issue by T-Hishinuma0821** [Lalcs/jpholiday#29]
## 概要
最新のRelease versionが`v0.1.8`である一方で、最新のTag versionが`v0.18`であり、現状不一致です。
最新のTag versionを`v0.1.8`にそろえていただけませんでしょうか

**Comment by Lalcs** [comment]
ありがとうございます。
こちら変更しましたのでクローズします。
