### ISSUE TITLE
祝日関する法律制定年について

### ISSUE THREAD

**Issue by mlove4u** [Lalcs/jpholiday#3]
法律制定年この辺に不備があったようです。
例として：
天皇誕生日（平成以降）
jpholiday.year_holidays(1948)-->(datetime.date(1948, 12, 23), '天皇誕生日')：X
振替休日（1973年以降）
jpholiday.year_holidays(1971)-->(datetime.date(1971, 10, 11), '体育の日 振替休日')：X
ご確認よろしくお願いします。

**Comment by Lalcs** [comment]
ご連絡ありがとうございます。
近日中に対応いたします。

**Comment by Lalcs** [comment]
上記にて対応
