### ISSUE TITLE
土日＋カスタム祝日も含ませる拡張機能

### ISSUE THREAD

**Issue by kujiy** [Lalcs/jpholiday#6]
便利なライブラリ、ありがとうございます。令和対応まで感謝です。

jpholidayの対応範囲ではないことを知りつつもリクエストさせていただきたいです。

1. 土日の場合もTrueを返すオプション
2. 祝日を追加設定できる（会社の創立記念日、12/30-1/4は毎年休みにする、など）

今は自作しているのですが、jpholidayにこの機能があればいいなと思いました。
もしくは、jpholidayをwrapしたそのようなライブラリがあれば、教えていただきたいです。

**Comment by Lalcs** [comment]
v0.1.0で祝日の追加に対応しましたので、ご利用ください。

**Comment by kujiy** [comment]
おおおマジですか！！ありがとうございました！！
